services:
  - type: web
    name: whisperx-backend
    env: docker
    plan: free
    buildCommand: ""  # not needed in Docker mode
    startCommand: ""  # use CMD from Dockerfile
    dockerfilePath: backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
